cargo new --lib circle
cargo new --lib card_deck
cargo new --lib arrays
cargo new --lib strings
cargo new --lib capitalizing
cargo new --lib edit_distance
cargo new --lib simple_hash
cargo new --lib bigger
cargo new --lib string_permutation
cargo new --lib hashing
cargo new --lib collect
cargo new --lib is_anagram
